### ISSUE TITLE
Countdown isn‘t working

### ISSUE THREAD

**Issue by github-host2** [MitkoVtori/worldcup-countdown#27]
The countdown isn‘t working.

![7BF830A4-D6D1-40E5-81D5-44387A985ABA](https://user-images.githubusercontent.com/110337548/210341794-2a617a85-5587-40ed-9b5b-33554fa317af.jpeg)

**Comment by MitkoVtori** [comment]
hmm, I don't know. for me it is working, also on my phone:
![Screenshot 2023-01-03 131536](https://user-images.githubusercontent.com/112943652/210347199-15cc8dac-9514-4640-9cd2-12873b12dba1.png)

I will ask one friend from Germany if he can see it.

**Comment by github-host2** [comment]
> I am from Germany 😀. Here some Device Details for you.

**Device Details**

Apple IPad 9. Generation with WiFi and 64 GB Storage

**Browser Details**

Microsoft Edge for IPad

No proxy or DNS activated

**WiFi**

No settings for deactivate JavaScript or something other activated

**Comment by MitkoVtori** [comment]
Unfortunatelly, the problem Is somewhere in your device. My friend say it works for him, so it's not from the code or the country.
I am unable to help in this situation. Anyways, you can copy the repo and try run it on your local host. 
if you need help with it, I can show you how.

**Comment by github-host2** [comment]
Thanks, but I know how to. I have a Apache HTTP Server on my computer (😁) and if that not work I know how to use the network storage via WiFi (🖥️).
